# Specify the version of the Yaml File,
# can be higher depending on Docker Engine.
version: '3.0'

# Specify the specific services (containers)
# that will make up the pipeline
services:
  
  # Build a Mongo container from the current
  # mongo image.
  mongodb:
    image: mongo
    container_name: mongo_reddit
    ports: 
      - 27017:27017

  # Build a self-made container
  reddit_collector:

    # Tells Docker where to find the
    # Dockerfile
    build: ./reddit_collector/

    # Naming the container for clarity
    container_name: reddit_container

    # Tells Docker where to find necessary
    # files and where to put them.
    volumes:
      - ./reddit_collector/:/app
    
    # Connects this container to another container
    depends_on:
      - mongodb

    # Keeps certain aspects secret i.e. passwords
    env_file:
      - .env

  # Build a Postgres container from image    
  postgresdb:
    image: postgres
    container_name: post_reddit

    # Left number is local, right number is the container
    ports:
      - 5555:5432

    # Create specific names and passwords to be used later
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=redditdb
    
  etl:
    build: ./etl_job/
    container_name: etl_container
    volumes:
      - ./etl_job/:/app
    depends_on:
      - mongodb
      - postgresdb

  slackbot:
    build: ./slackbot_job/
    container_name: slack_bot
    volumes:
      - ./slackbot_job/:/app
    depends_on:
      - postgresdb
    env_file:
      - .env
